"""Actionable status/error reports without touching hardware or publishing messages."""

from __future__ import annotations

import subprocess
import sys
import zipapp
from dataclasses import replace
from pathlib import Path

import pytest

from lsh_stack_config import __version__, cli, cli_runtime, scaffold, status
from lsh_stack_config.composer import compose_stack
from lsh_stack_config.core_export import load_core_export
from lsh_stack_config.errors import StackConfigError
from lsh_stack_config.models import JsonObject, StackConfig
from lsh_stack_config.parser import load_stack_config
from lsh_stack_config.render import write_output_tree
from test_stack_config import _core_export


@pytest.fixture
def configured_stack(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[StackConfig, JsonObject]:
    """Provide a complete isolated project with a mocked controller export."""
    root = tmp_path / "home"
    scaffold.write_starter(root, force=False)
    config = load_stack_config(root / "lsh_stack.toml")
    tool = root / "generator.py"
    tool.touch()
    config = replace(config, core=replace(config.core, tool=tool))
    stack = compose_stack(config, _core_export())
    write_output_tree(root / "generated", config, stack)
    monkeypatch.setattr(status, "load_core_export", lambda _config: _core_export())
    monkeypatch.setattr(cli_runtime, "platformio_invocation", lambda: ["platformio"])
    monkeypatch.setattr(cli, "_compose", lambda _path: (config, stack))
    monkeypatch.chdir(root)
    return config, stack


@pytest.mark.parametrize(
    ("core_local", "bridge_local"), [(False, False), (True, True), (True, False)]
)
def test_status_identifies_generator_and_dependency_selection(
    configured_stack: tuple[StackConfig, JsonObject], *, core_local: bool, bridge_local: bool
) -> None:
    """Status exposes the code being used and never completes a switch itself."""
    config, _ = configured_stack
    root = config.path.parent
    for name, local in (("core", core_local), ("bridge", bridge_local)):
        if local:
            (root / name / "platformio.local.ini").write_text(
                "; Generated by lsh-stack dev.\n", encoding="utf-8"
            )
    before = {p: p.read_bytes() for p in root.rglob("*") if p.is_file()}
    report = status.render_stack_status(status.inspect_stack_status(config, root / "generated"))
    assert f"generator: lsh-stack {__version__}" in report
    assert f"generator path: {Path(status.__file__).parent}" in report
    assert "launcher: python " in report
    assert f"core {'local' if core_local else 'release'}" in report
    assert f"bridge {'local' if bridge_local else 'release'}" in report
    assert "generated content: current" in report
    next_action = report.split("next action:\n")[1]
    if core_local != bridge_local:
        assert "complete the dependency switch" in next_action
        assert " dev local" in next_action
        assert " dev release" in next_action
    else:
        assert " core build --all" in next_action
    assert before == {p: p.read_bytes() for p in root.rglob("*") if p.is_file()}


def test_status_does_not_label_custom_overrides_as_release_or_local(
    configured_stack: tuple[StackConfig, JsonObject],
) -> None:
    """Unknown overrides remain visible and are left for manual correction."""
    config, _ = configured_stack
    override = config.path.parent / "core/platformio.local.ini"
    override.write_text("; custom dependencies\n", encoding="utf-8")
    report = status.render_stack_status(
        status.inspect_stack_status(config, config.path.parent / "generated")
    )
    assert "dependencies: not verified: custom override left untouched" in report
    assert "move it aside first" in report
    assert " dev status" in report.split("next action:\n")[1]
    assert override.read_text(encoding="utf-8") == "; custom dependencies\n"


def test_invalid_config_takes_priority_over_missing_outputs(
    configured_stack: tuple[StackConfig, JsonObject], monkeypatch: pytest.MonkeyPatch
) -> None:
    """An invalid source config needs diagnosis before regenerating its missing files."""
    config, _ = configured_stack
    (config.path.parent / "generated/system-config.json").unlink()

    def fail(_config: object) -> JsonObject:
        raise StackConfigError("unknown actuator: typo")

    monkeypatch.setattr(status, "load_core_export", fail)
    report = status.render_stack_status(
        status.inspect_stack_status(config, config.path.parent / "generated")
    )
    assert "configuration: invalid: unknown actuator: typo" in report
    assert " doctor" in report.split("next action:\n")[1]


@pytest.mark.parametrize(
    "command",
    [["core", "build", "typo"], ["bridge", "upload", "typo"], ["ota", "typo"], ["explain", "typo"]],
)
def test_unknown_device_lists_valid_targets_without_running_an_operation(
    configured_stack: tuple[StackConfig, JsonObject],
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
    command: list[str],
) -> None:
    """The failing command tells the user how to correct its target immediately."""
    config, _ = configured_stack
    monkeypatch.setattr(cli, "_validate_stack_ota_support", lambda _config: None)
    monkeypatch.setattr(cli, "run_or_print", lambda *_args, **_kwargs: pytest.fail("operation"))
    assert cli.main(command) == 2
    error = capsys.readouterr().err
    assert "typo" in error
    assert "Known devices:" in error
    assert "panel" in error
    assert "lights" in error
    assert (config.path.parent / "generated/system-config.json").is_file()


@pytest.mark.parametrize("kind", ["core", "bridge"])
@pytest.mark.usefixtures("configured_stack")
def test_unknown_profile_lists_available_profiles_and_listing_command(
    capsys: pytest.CaptureFixture[str],
    kind: str,
) -> None:
    """Core and bridge use the same actionable profile selection errors."""
    args = [kind, "build"]
    if kind == "core":
        args.append("panel")
    args.extend(["--profile", "typo"])
    assert cli.main(args) == 2
    error = capsys.readouterr().err
    assert "Available profiles:" in error
    assert "release" in error
    assert "debug" in error
    assert f" {kind} list" in error


def test_doctor_provides_repair_commands_for_custom_config_path(
    configured_stack: tuple[StackConfig, JsonObject],
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """The repair command keeps the current launcher and a quoted custom config."""
    config, stack = configured_stack
    config = replace(config, path=config.path.parent / "custom stack.toml")
    monkeypatch.setattr(cli, "_compose", lambda _path: (config, stack))
    (config.path.parent / "generated/platformio-core-targets.py").unlink()
    assert cli.main(["doctor", "--config", str(config.path)]) == 1
    output = capsys.readouterr().out
    assert "missing or unreadable generated/platformio-core-targets.py" in output
    assert "generate --config 'custom stack.toml'" in output
    assert "doctor --config 'custom stack.toml'" in output


def test_missing_explicit_generator_explains_override_recovery(
    configured_stack: tuple[StackConfig, JsonObject],
) -> None:
    """A stale tool override must be corrected rather than silently replaced."""
    config, _ = configured_stack
    missing = config.path.parent / "missing-generator.py"
    with pytest.raises(StackConfigError) as exc:
        load_core_export(replace(config.core, tool=missing))
    assert str(missing) in str(exc.value)
    assert "[core].tool or LSH_CORE_TOOL" in str(exc.value)
    assert " setup`" in str(exc.value)


def test_zipapp_status_reports_archive_actually_running(tmp_path: Path) -> None:
    """Exercise real zip imports so a packaged launcher cannot look like the checkout."""
    source = Path(__file__).parents[1] / "src"
    archive = tmp_path / "release bundle" / "lsh-stack.pyz"
    archive.parent.mkdir()
    zipapp.create_archive(source, target=archive, main="lsh_stack_config.cli:entrypoint")
    project = tmp_path / "installation"
    subprocess.run(  # noqa: S603 - isolated generated launcher
        [sys.executable, str(archive), "new", str(project)], check=True, capture_output=True
    )
    launcher = project / archive.name
    result = subprocess.run(  # noqa: S603 - isolated generated launcher, read-only status
        [sys.executable, str(launcher), "status"],
        cwd=project / "core",
        check=True,
        capture_output=True,
        text=True,
    )
    assert f"generator: lsh-stack {__version__}" in result.stdout
    assert f"generator path: {launcher}/lsh_stack_config" in result.stdout
    assert str(launcher) in result.stdout.split("- launcher: ")[1].splitlines()[0]
    assert str(source) not in result.stdout
