"""Opt-in local library overrides; release pins remain in the project INI files."""

from __future__ import annotations

import fnmatch
import io
import os
import re
import shutil
import sys
from pathlib import Path

from .errors import StackConfigError
from .models import StackConfig
from .platformio_utils import (
    PLATFORMIO_CONFIG_ERRORS,
    load_platformio_config,
    option_values,
    section_refs,
)

_MARKER = "; Generated by lsh-stack dev.\n"
_LEGACY_MARKER = "; Generated by scripts/local_dev.py."
_LIBRARIES = {"lsh-core": "lsh-core", "lsh-bridge": "lsh-bridge", "homie-v5": "homie-esp8266"}


def _projects(config: StackConfig) -> tuple[Path, Path]:
    return (
        config.platformio.core_project or config.core.devices.parent,
        config.platformio.bridge_project or config.path.parent / "bridge",
    )


def development_status(config: StackConfig) -> int:
    """Report both projects, including incomplete switches and foreign overrides."""
    present = dependency_modes(config)
    for project, local in zip(_projects(config), present, strict=True):
        sys.stdout.write(f"{project.name}: {'local' if local else 'release'}\n")
    if any(present) and not all(present):
        sys.stderr.write("Incomplete dependency switch; run dev local or dev release.\n")
        return 1
    return 0


def dependency_modes(config: StackConfig) -> tuple[bool, bool]:
    """Read the managed dependency selection for both projects without changing it."""
    core, bridge = _projects(config)
    for project in (core, bridge):
        _validate_project(project)
    return (core / "platformio.local.ini").is_file(), (bridge / "platformio.local.ini").is_file()


def switch_dependencies(config: StackConfig, repositories: Path, *, local: bool) -> Path | None:
    """Validate both projects before switching only owned files and disposable build state."""
    projects = _projects(config)
    if projects[0].resolve() == projects[1].resolve():
        raise StackConfigError("dev requires separate core and bridge project directories.")
    tool = repositories / "lsh-core" / "tools" / "generate_lsh_static_config.py"
    if local:
        required = [repositories / name / "library.json" for name in _LIBRARIES.values()]
        required.append(tool)
        missing = [str(path) for path in required if not path.is_file()]
        if missing:
            raise StackConfigError("missing local repositories/tools:\n" + "\n".join(missing))
    overrides: dict[Path, str | None] = {}
    for project, required_libraries in zip(
        projects, ({"lsh-core"}, {"lsh-bridge", "homie-v5"}), strict=True
    ):
        path = project / "platformio.local.ini"
        _validate_project(project)
        overrides[path] = (
            _local_override(project, repositories, required_libraries) if local else None
        )
    _apply_overrides(overrides)
    sys.stdout.write(f"{'Local' if local else 'Release'} dependencies selected.\n")
    return tool if local else None


def _apply_overrides(overrides: dict[Path, str | None]) -> None:
    before = {path: path.read_bytes() if path.exists() else None for path in overrides}
    try:
        for path, content in overrides.items():
            if content is None:
                path.unlink(missing_ok=True)
            else:
                path.write_text(content, encoding="utf-8")
        # Reusing a release package or object in local mode (or vice versa) is unsafe.
        for path, content in overrides.items():
            if before[path] == (None if content is None else content.encode("utf-8")):
                continue
            state = path.parent / ".pio"
            if state.exists():
                shutil.rmtree(state)
    except OSError as exc:
        for path, previous in before.items():
            if previous is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(previous)
        raise StackConfigError(
            f"dependency switch failed: {exc}; rerun setup before building."
        ) from exc


def _validate_project(project: Path) -> None:
    path = project / "platformio.local.ini"
    _check_managed(path)
    if not (project / "platformio.ini").is_file():
        raise StackConfigError(f"missing {project / 'platformio.ini'}; run setup first.")
    # Never follow a build directory symlink when discarding cached packages.
    if (project / ".pio").is_symlink():
        raise StackConfigError(f"refusing to clear symlinked build directory: {project / '.pio'}")
    for other in project.glob("platformio.local*.ini"):
        if other != path:
            raise StackConfigError(f"move custom override {other} aside before using dev.")


def _check_managed(path: Path) -> None:
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise StackConfigError(f"refusing to change non-regular override: {path}")
    if path.exists():
        try:
            managed = path.read_text(encoding="utf-8").startswith((_MARKER, _LEGACY_MARKER))
        except (OSError, UnicodeDecodeError) as exc:
            raise StackConfigError(f"cannot read override {path}: {exc}") from exc
        if not managed:
            raise StackConfigError(f"custom override left untouched: {path}; move it aside first.")


def _local_override(project: Path, repositories: Path, required: set[str]) -> str:
    try:
        parser = load_platformio_config(project / "platformio.ini")
    except PLATFORMIO_CONFIG_ERRORS as exc:
        raise StackConfigError(f"cannot read {project / 'platformio.ini'}: {exc}") from exc
    includes = section_refs(parser.get("platformio", "extra_configs", fallback=""))
    if not any(fnmatch.fnmatch("platformio.local.ini", entry) for entry in includes):
        raise StackConfigError(
            f"add platformio.local*.ini to [platformio].extra_configs "
            f"in {project / 'platformio.ini'}."
        )
    replaced: set[str] = set()
    # Keep all non-local dependencies verbatim, including project-specific pins.
    for section in list(parser.sections()):
        dependencies = option_values(parser.get(section, "lib_deps", fallback=""))
        changed = False
        for index, dependency in enumerate(dependencies):
            match = re.fullmatch(
                r"(?:labodj/)?(lsh-core|lsh-bridge|homie-v5)(?:\s*@\s*.+)?", dependency
            )
            if match is None:
                continue
            name = match[1]
            repository = repositories / _LIBRARIES[name]
            try:
                relative = Path(os.path.relpath(repository, project)).as_posix()
            except ValueError:
                relative = repository.as_posix()
            dependencies[index] = f"{name}=symlink://{relative}"
            replaced.add(name)
            changed = True
        if not changed:
            parser.remove_section(section)
            continue
        for option in list(parser[section]):
            parser.remove_option(section, option)
        parser.set(section, "lib_deps", "\n" + "\n".join(dependencies))
    if missing := required - replaced:
        raise StackConfigError(
            f"declare release lib_deps for {', '.join(sorted(missing))} "
            f"in {project / 'platformio.ini'} before switching to local libraries."
        )
    buffer = io.StringIO()
    parser.write(buffer)
    return _MARKER + buffer.getvalue()
